openapi: 3.0.0
info:
  title: Device Management API
  version: 1.0.0
  description: Управление IoT-устройствами

paths:
  /devices:
    post:
      summary: Регистрация устройства
      description: Регистрирует новое IoT-устройство в системе
      tags:
        - Devices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - serialNumber
                - typeId
                - houseId
              properties:
                serialNumber: 
                  type: string
                  description: Серийный номер устройства
                  example: "SN-TH-001"
                typeId:
                  type: string
                  format: uuid
                  description: Идентификатор типа устройства
                  example: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                houseId:
                  type: string
                  format: uuid
                  description: Идентификатор дома
                  example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        '201':
          description: Устройство успешно зарегистрировано
          content:
            application/json:
              schema:
                type: object
                properties:
                  deviceId:
                    type: string
                    format: uuid
                    description: Уникальный идентификатор устройства
                    example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                  status:
                    type: string
                    enum: [ACTIVE, INACTIVE, PENDING]
                    description: Текущий статус устройства
                    example: "ACTIVE"
                  firmwareVersion:
                    type: string
                    description: Версия прошивки устройства
                    example: "1.2.3"
        '400':
          description: Неверные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Устройство с таким серийным номером уже существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /devices/{deviceId}/commands:
    post:
      summary: Отправить команду устройству
      description: Отправляет команду управления на указанное устройство
      tags:
        - Device Commands
      parameters:
        - name: deviceId
          in: path
          required: true
          description: Уникальный идентификатор устройства
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - commandType
                - parameters
              properties:
                commandType:
                  type: string
                  description: Тип команды
                  enum: [SET_TEMPERATURE, SET_MODE, TURN_ON, TURN_OFF]
                  example: "SET_TEMPERATURE"
                parameters:
                  type: object
                  description: Параметры команды в зависимости от типа
                  example:
                    value: 22.5
                    unit: "C"
      responses:
        '202':
          description: Команда успешно принята к исполнению
          content:
            application/json:
              schema:
                type: object
                properties:
                  commandId:
                    type: string
                    format: uuid
                    description: Уникальный идентификатор команды
                    example: "d4f3b6a0-8e7a-4b8c-9d1a-2e3f4d5c6b7a"
                  status:
                    type: string
                    enum: [QUEUED, SENT, DELIVERED, EXECUTED, FAILED]
                    description: Статус выполнения команды
                    example: "QUEUED"
        '404':
          description: Устройство не найдено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          description: Код ошибки
        message:
          type: string
          description: Описание ошибки 